### ISSUE TITLE
Strange behavior of the indentation algorithm

### ISSUE THREAD

**Issue by matej-kosik** [ocaml/tuareg#98]
I am using Emacs for editing Ocaml code.
I have noticed, that in some cases, the behavior of the indentation algorithm is strange.

For example when I type the following code

``` Ocaml
type 'a foo = 'a option =
            | None
            | Some of 'a
```

and I let Emacs reindent it automatically, I get this:

``` Ocaml
type 'a foo = 'a option =
            | None
              | Some of 'a
```

Which is strange, isn't it?

It seems to be confused by the additional type equality. If I remove the type equality, the indenting algorithm behaves reasonably. I get:

``` Ocaml
type 'a foo =
  | None
  | Some of 'a
```

This is how my `.emacs` file looks like:

```
(push "~/.opam/4.02.3/share/emacs/site-lisp" load-path)     ; directory containing merlin.el
(setq merlin-command "~/.opam/4.02.3/bin/ocamlmerlin")      ; needed only if ocamlmerlin not already in your PATH
(autoload 'merlin-mode "merlin" "Merlin mode" t)
(add-hook 'tuareg-mode-hook 'merlin-mode)
(add-hook 'caml-mode-hook 'merlin-mode)
(load "~/.opam/4.02.3/share/emacs/site-lisp/tuareg-site-file")
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(inhibit-startup-screen t)
 '(merlin-locate-in-new-window (quote never))
 '(safe-local-variable-values
   (quote
    ((eval progn
           (let
               ((coq-root-directory
                 (when buffer-file-name
                   (locate-dominating-file buffer-file-name ".dir-locals.el")))
                (coq-project-find-file
                 (and
                  (boundp
                   (quote coq-project-find-file))
                  coq-project-find-file)))
             (set
              (make-local-variable
               (quote tags-file-name))
              (concat coq-root-directory "TAGS"))
             (setq camldebug-command-name
                   (concat coq-root-directory "dev/ocamldebug-coq"))
             (unless coq-project-find-file
               (set
                (make-local-variable
                 (quote compile-command))
                (concat "make -C " coq-root-directory))
               (set
                (make-local-variable
                 (quote compilation-search-path))
                (cons coq-root-directory nil)))
             (when coq-project-find-file
               (setq default-directory coq-root-directory))))
     (eval progn
           (let
               ((coq-root-directory
                 (when buffer-file-name
                   (locate-dominating-file buffer-file-name ".dir-locals.el")))
                (coq-project-find-file
                 (and
                  (boundp
                   (quote coq-project-find-file))
(push "~/.opam/4.02.3/share/emacs/site-lisp" load-path)     ; directory containing merlin.el
(setq merlin-command "~/.opam/4.02.3/bin/ocamlmerlin")      ; needed only if ocamlmerlin not already in your PATH
(autoload 'merlin-mode "merlin" "Merlin mode" t)
(add-hook 'tuareg-mode-hook 'merlin-mode)
(add-hook 'caml-mode-hook 'merlin-mode)
(load "~/.opam/4.02.3/share/emacs/site-lisp/tuareg-site-file")
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(inhibit-startup-screen t)
 '(merlin-locate-in-new-window (quote never))
 '(safe-local-variable-values
   (quote
    ((eval progn
           (let
               ((coq-root-directory
                 (when buffer-file-name
                   (locate-dominating-file buffer-file-name ".dir-locals.el")))
                (coq-project-find-file
                 (and
                  (boundp
                   (quote coq-project-find-file))
                  coq-project-find-file)))
             (set
              (make-local-variable
               (quote tags-file-name))
              (concat coq-root-directory "TAGS"))
             (setq camldebug-command-name
                   (concat coq-root-directory "dev/ocamldebug-coq"))
             (unless coq-project-find-file
               (set
                (make-local-variable
                 (quote compile-command))
                (concat "make -C " coq-root-directory))
               (set
                (make-local-variable
                 (quote compilation-search-path))
                (cons coq-root-directory nil)))
             (when coq-project-find-file
               (setq default-directory coq-root-directory))))
     (eval progn
           (let
               ((coq-root-directory
                 (when buffer-file-name
                   (locate-dominating-file buffer-file-name ".dir-locals.el")))
                (coq-project-find-file
                 (and
                  (boundp
                   (quote coq-project-find-file))
                  coq-project-find-file)))
             (set
              (make-local-variable
               (quote tags-file-name))
              (concat coq-root-directory "TAGS"))
             (setq camldebug-command-name
                   (concat coq-root-directory "ocamldebug"))
             (unless coq-project-find-file
               (set
                (make-local-variable
                 (quote compile-command))
                (concat "make -C " coq-root-directory))
               (set
                (make-local-variable
                 (quote compilation-search-path))
                (cons coq-root-directory nil)))
             (when coq-project-find-file
               (setq default-directory coq-root-directory)))))))
 '(send-mail-function (quote mailclient-send-it))
 '(tuareg-electric-indent nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

; merlin
(global-set-key (kbd "C-l") 'merlin-locate)
(global-set-key (kbd "C-b") 'merlin-pop-stack)
(global-set-key (kbd "C-t") 'merlin-type-enclosing)

; ocamldebug
(global-set-key (kbd "<f5>") 'ocamldebug-break)
(global-set-key (kbd "<f6>") 'ocamldebug-run)
(global-set-key (kbd "<f7>") 'ocamldebug-next)
(global-set-key (kbd "<f8>") 'ocamldebug-step)
(global-set-key (kbd "<f9>") 'ocamldebug-finish)
(global-set-key (kbd "<f10>") 'ocamldebug-print)
(global-set-key (kbd "<f12>") 'camldebug)

(package-initialize)
(require 'company)
(add-to-list 'company-backends 'merlin-company-backend)
(add-hook 'merlin-mode-hook 'company-mode)
(global-set-key [C-tab] 'company-complete)

;; Do not use TABs. These confuse Merlin.
(setq-default indent-tabs-mode nil)

;; Automatically scroll the window containing the compilation output.
(setq compilation-scroll-output t)

;; show column number in addition to the line-number
(column-number-mode)
```

**Comment by monnier** [comment]
Interesting.  I'm not familiar with that syntax, so it's no surprise that my SMIE code doesn't handle it correctly.  Could you point me to the documentation that explains what it means (and what is its syntax, in the more general case)?

**Comment by matej-kosik** [comment]
The corresponding non-terminal in Ocaml grammar is called [type-equation](http://caml.inria.fr/pub/docs/manual-ocaml/typedecl.html#type-equation).

The meaning is described in the same section as:

> The two components of a type definition, the optional _equation_ and the optional _representation_, can be combined independently, giving rise to four typical situations:
>
> **Abstract type: no equation, no representation.**
>
> When appearing in a module signature, this definition specifies nothing on the type constructor, besides its number of parameters: its representation is hidden and it is assumed incompatible with any other type.
> 
> **Type abbreviation: an equation, no representation.**
>
> This defines the type constructor as an abbreviation for the type expression on the right of the `=` sign.
>
> **New variant type or record type: no equation, a representation.**
>
> This generates a new type constructor and defines associated constructors or fields, through which values of that type can be directly built or inspected.
>
> **Re-exported variant type or record type: an equation, a representation.**
>
> In this case, the type constructor is defined as an abbreviation for the type expression given in the equation, but in addition the constructors or fields given in the representation remain attached to the defined type constructor. The type expression in the equation part must agree with the representation: it must be of the same kind (record or variant) and have exactly the same constructors or fields, in the same order, with the same arguments.

Even though the grammar suggests that one can add optional type-equations to any kind of type, in practise this is allowed (and only makes sense) for variants and records.

**Comment by matej-kosik** [comment]
It may look arcane at first, but it is fairly logical stuff.

**Comment by moosotc** [comment]
Same (?) thing happens with simple
`function
| A
  | B`

**Comment by matej-kosik** [comment]
To @moosotc, I am not sure if I understand.

**Comment by moosotc** [comment]
Matej Košík <notifications@github.com> writes:

> To @moosotc, I am not sure if I understand.

I will use '.' to indicate leading spaces,
'
function
| A
..| B
'

This is how tuareg indents this, IOW the problem is that pipes are
misaligned.

Following is OTOH fine:
'
function
| A -> stuff
| B -> otherstuff
'

-- 
mailto:moosotc@gmail.com

**Comment by matej-kosik** [comment]
Ok. I understand. I am not sure whether this is the same problem as the one I described above.

Because this:
```Ocaml
type bar = A
         | B
```
works fine. The fact that
```Ocaml
function
| A
  | B -> (* some stuff *)
```
is formatted in a "funny" way may be a separate problem. Separate github-issue, perhaps?

**Comment by moosotc** [comment]
Matej Košík <notifications@github.com> writes:

> Ok. I understand. I am not sure whether this is the same problem as the one I described above.
>
> Because this:
> ```Ocaml
> type bar = A
>          | B
> ```
> works fine. The fact that
> ```Ocaml
> function
> | A
>   | B -> (* some stuff *)
> ```
> is formatted in a "funny" way may be a separate problem. Separate github-issue, perhaps?

Yeah, most likely, thanks for heads up.

-- 
mailto:moosotc@gmail.com

**Comment by Chris00** [comment]
This is not the same issue as the original one.  For `function |A | B ...`, see https://github.com/ocaml/tuareg/issues/78

**Comment by monnier** [comment]
Hmm... sorry for taking so long to get back.  But now I just tried it and can't reproduce the behavior you describe.  I did

    emacs24 -Q -l tuareg-autoloads.el indent-test.ml

and then inserted your example and re-indented it by hand, and that gave me:

    type 'a foo = 'a option =
        | None
        | Some of 'a

Has the problem been fixed in the mean time (I used the latest tuareg.el from Git)?

**Comment by matej-kosik** [comment]
I observe this behavior with latest `tuareg` package distributed via OPAM (2.0.10) with Ocaml 4.02.3 with Emacs 24.4.1.

My `~/.emacs` file contains the following line:
```
(load "~/.opam/4.02.3/share/emacs/site-lisp/tuareg-site-file")
```

**Comment by Chris00** [comment]
The indentation @monnier has is a consequence of [this commit](https://github.com/ocaml/tuareg/commit/95bbf6f2237424337ee27f077ee240e383aafc28) that we [are discussing](https://github.com/ocaml/tuareg/issues/7#issuecomment-270939047).  So it is partially fixed—the amount of indentation is not yet right.

**Comment by monnier** [comment]
I installed a further patch to refine `tuareg-smie--=-disambiguate` so as to handle this case properly.

**Comment by matejkosik** [comment]
At the moment, in my case, the Tuareg-related line in my `~/.emacs` file has the following form:
```
(load "~/.opam/4.02.3/share/emacs/site-lisp/tuareg-site-file")
```
Where are users supposed to put `tuareg-smie--=-disambiguate` you mention above if they want to take advantage of this feature?

**Comment by Chris00** [comment]
If you are in a hurry, clone the repository and load its `tuareg-site-file`.  Alternatively, Tuareg is in [melpa](http://melpa.org/) so you can install it through `M-x package-install` (remove the `opam` package then).   I plan to do a release "soon"—after which you only have to do an `opam update && opam upgrade`—but there are still a few issues I'd like to tackle before that.
